controls:
    gpio.pause: 25
    gpio.skip: 18
    gpio.like: 24
    gpio.dislike: 23
    gpio.station_down: 22
    gpio.station_up: 27
    gpio.volume_down: 4
    gpio.volume_up: 17


input_fifo: input.fifo
pandora_ctl: /home/pi/.config/pianobar/ctl
pandora_station: /var/pandora_station

sound_out: PCM
current_volume: /var/volume_number
volumes:
    - 0
    - 60
    - 65
    - 70
    - 75
    - 77
    - 80
    - 83
    - 85
    - 88
    - 90
    - 95
